version: "2"
services:
  redis:
    image: redis:3.0
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"